In [3]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
import pandas as pd

In [4]:
# Create a dictionary containing the data
data = {
    'Years of Exp': [1, 1.5, 2.5, 3, 5, 6],
    'Gap': [0, 1, 1, 0, 0, 0],
    'Annual salary': [4, 4, 5.5, 7, 7.5, 8]
}
# Create a pandas DataFrame from the dictionary
df = pd.DataFrame(data)

X=df.drop('Annual salary',axis=1)
Y=df["Annual salary"]

In [5]:
# Create a decision tree regressor with a maximum depth of 1
predicted_values = np.full_like(Y, np.mean(Y))
print("base -predicted:", predicted_values)
error_values = np.array(Y - np.mean(Y))
print("base-errors",error_values)

for i in range(30):
    
    tree_reg = DecisionTreeRegressor(max_depth=1)
    tree_reg.fit(X, error_values)

    # Find the average target value in each leaf node
    # Leaf nodes can be found using the tree's `apply` method
    leaf_nodes = tree_reg.apply(X)

    leaf_values = {}
    for node in set(leaf_nodes):
        leaf_values[node] = error_values[leaf_nodes == node].mean()

    # Create a target column based on the average target value of the leaf node
    target_column = np.array([leaf_values[node] for node in leaf_nodes])

    # Print the target column
    print("Target column based on leaf node averages:")
    print(target_column)
    predicted_values=predicted_values+0.1*(target_column)
    print("base -predicted:", predicted_values)
    error_values = np.array(Y - predicted_values)
    
    print("base-errors",error_values)
    print("=============================================")

# test set RMSE
test_rmse = mean_squared_error(Y, predicted_values) ** (1 / 2)
 
# Print rmse
print('Root mean Square error: {:.2f}'.format(test_rmse))

base -predicted: [6. 6. 6. 6. 6. 6.]
base-errors [-2.  -2.  -0.5  1.   1.5  2. ]
Target column based on leaf node averages:
[-1.5 -1.5 -1.5  1.5  1.5  1.5]
base -predicted: [5.85 5.85 5.85 6.15 6.15 6.15]
base-errors [-1.85 -1.85 -0.35  0.85  1.35  1.85]
Target column based on leaf node averages:
[-1.35 -1.35 -1.35  1.35  1.35  1.35]
base -predicted: [5.715 5.715 5.715 6.285 6.285 6.285]
base-errors [-1.715 -1.715 -0.215  0.715  1.215  1.715]
Target column based on leaf node averages:
[-1.215 -1.215 -1.215  1.215  1.215  1.215]
base -predicted: [5.5935 5.5935 5.5935 6.4065 6.4065 6.4065]
base-errors [-1.5935 -1.5935 -0.0935  0.5935  1.0935  1.5935]
Target column based on leaf node averages:
[-1.5935  -1.5935   0.79675  0.79675  0.79675  0.79675]
base -predicted: [5.43415  5.43415  5.673175 6.486175 6.486175 6.486175]
base-errors [-1.43415  -1.43415  -0.173175  0.513825  1.013825  1.513825]
Target column based on leaf node averages:
[-1.43415  -1.43415   0.717075  0.717075  0.717075  0.

In [6]:
# Create and fit the gradient boosting regressor model
from sklearn.ensemble import GradientBoostingRegressor
gb_regressor = GradientBoostingRegressor(loss='absolute_error',n_estimators=30)
gb_regressor.fit(X, Y)

# Predict on the test set
Y_pred = gb_regressor.predict(X)

# Calculate Mean Squared Error (MSE)
rmse = mean_squared_error(Y, Y_pred) ** (1 / 2)
print("Root Mean Squared Error:", rmse)

Root Mean Squared Error: 0.33509607056228347
